language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8-dev
      dist: xenial
      sudo: true

install:
    - python setup.py install
    - pip install -r requirements-dev.txt

script:
    - nosetests

